<a href="https://colab.research.google.com/github/Aleeha-Fatima-del/task03_aleeha-fatima/blob/main/Week_3_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
file_path = '/content/Dataset for Data Analytics (3).xlsx'
df = pd.read_excel(file_path)
display(df.head())

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
import sqlite3

In [ ]:
# SQLite database creation
conn = sqlite3.connect("orders.db")

# Insert DataFrame into SQL table
df.to_sql("Orders", conn, if_exists="replace", index=False)

1200

### Select first 5 rows

In [ ]:
display(pd.read_sql("SELECT * FROM Orders LIMIT 5;", conn))

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

### Delivered orders

In [ ]:
display(pd.read_sql("SELECT OrderID, Product, TotalPrice FROM Orders WHERE OrderStatus='Delivered';", conn))

       OrderID  Product  TotalPrice
0    ORD200004  Printer     2504.04
1    ORD200015  Printer      473.96
2    ORD200021  Monitor     1371.80
3    ORD200024   Laptop      461.90
4    ORD200025  Monitor      399.98
..         ...      ...         ...
226  ORD201166    Chair      973.41
227  ORD201168   Laptop      662.84
228  ORD201171    Phone     2073.60
229  ORD201187     Desk      369.20
230  ORD201197   Tablet      873.68

[231 rows x 3 columns]

### Sort by TotalPrice

In [ ]:
display(pd.read_sql("SELECT Product, TotalPrice FROM Orders ORDER BY TotalPrice DESC LIMIT 10;", conn))

   Product  TotalPrice
0   Tablet     3456.40
1  Monitor     3390.95
2   Laptop     3390.80
3    Chair     3384.90
4   Tablet     3370.20
5  Printer     3353.75
6   Laptop     3352.40
7  Printer     3334.00
8    Phone     3322.55
9   Laptop     3313.90

### Revenue per product

In [ ]:
display(pd.read_sql("""
SELECT Product, COUNT(*) AS TotalOrders, SUM(TotalPrice) AS Revenue, AVG(UnitPrice) AS AvgPrice
FROM Orders
GROUP BY Product
ORDER BY Revenue DESC;
""", conn))

   Product  TotalOrders    Revenue    AvgPrice
0    Chair          178  195620.11  355.660281
1  Printer          181  195612.61  351.714917
2   Laptop          173  192126.56  357.707052
3   Tablet          179  186568.95  367.679106
4  Monitor          163  175651.41  358.663620
5     Desk          170  167459.93  329.608118
6    Phone          156  151722.39  375.217564

### Coupon usage

In [ ]:
display(pd.read_sql("""
SELECT CouponCode, COUNT(*) AS UsageCount
FROM Orders
GROUP BY CouponCode
ORDER BY UsageCount DESC;
""", conn))

  CouponCode  UsageCount
0   FREESHIP         313
1       None         309
2   WINTER15         292
3     SAVE10         286

### Products with revenue > $2000

In [ ]:
display(pd.read_sql("""
SELECT Product, SUM(TotalPrice) AS Revenue
FROM Orders
GROUP BY Product
HAVING Revenue > 2000;
""", conn))

   Product    Revenue
0    Chair  195620.11
1     Desk  167459.93
2   Laptop  192126.56
3  Monitor  175651.41
4    Phone  151722.39
5  Printer  195612.61
6   Tablet  186568.95

### Payment method analysis

In [ ]:
display(pd.read_sql("""
SELECT PaymentMethod, COUNT(*) AS TotalOrders
FROM Orders
GROUP BY PaymentMethod
ORDER BY TotalOrders DESC;
""", conn))

  PaymentMethod  TotalOrders
0        Online          258
1          Cash          246
2   Credit Card          234
3    Debit Card          232
4     Gift Card          230

In [ ]:
print('--- Checking for duplicate OrderIDs ---')
display(pd.read_sql("SELECT OrderID, COUNT(*) as Count FROM Orders GROUP BY OrderID HAVING Count > 1;", conn))

print('\n--- Sampling Date format ---')
display(pd.read_sql("SELECT Date FROM Orders LIMIT 10;", conn))

--- Checking for duplicate OrderIDs ---

Empty DataFrame
Columns: [OrderID, Count]
Index: []

--- Sampling Date format ---

                  Date
0  2023-01-04 00:00:00
1  2024-08-23 00:00:00
2  2024-02-27 00:00:00
3  2023-10-15 00:00:00
4  2025-05-08 00:00:00
5  2023-10-23 00:00:00
6  2025-06-17 00:00:00
7  2023-05-12 00:00:00
8  2025-04-02 00:00:00
9  2023-11-21 00:00:00